#define KEY_GET_DATA 0
#define KEY_RECEIVED_DATA 1
#define KEY_ADD_PIN 2
#define KEY_DELETE_PIN 3
#define KEY_PIN_DATA 4
#define KEY_SUBSCRIBE_TOPIC 5
#define KEY_UNSUBSCRIBE_TOPIC 6

#define INFO_SESSION 10
#define IS_EMPLOYER 11
#define IS_EMPLOYER_INDEX 12
#define IS_DATE 13
#define IS_DATE_INDEX 14
#define IS_AMOUNT 15

#define LUNCH_MENU 20
#define LUNCH_SUBSCRIBED 21

#define DINNER_MENU 30
#define DINNER_SUBSCRIBED 31